import type { Benefit } from './types'

export const ANNUAL_FEE = 895

export const BENEFITS: Benefit[] = [
  {
    id: 'airline-fee',
    name: 'Airline Fee Credit',
    tagline: 'Up to $200 per year on incidental fees with your selected airline.',
    symbol: 'airplane',
    category: 'fixed',
    annualCap: 200,
    resetType: 'jan1',
  },
  {
    id: 'uber-cash',
    name: 'Uber Cash',
    tagline: '$15 monthly, plus a $20 December bonus — $200 a year on rides and Uber Eats.',
    symbol: 'car.fill',
    category: 'fixed',
    annualCap: 200,
    resetType: 'jan1',
  },
  {
    id: 'digital-entertainment',
    name: 'Digital Entertainment',
    tagline: 'Up to $20 a month on eligible streaming and digital subscriptions.',
    symbol: 'play.rectangle.fill',
    category: 'fixed',
    annualCap: 240,
    resetType: 'jan1',
  },
  {
    id: 'walmart-plus',
    name: 'Walmart+ Membership',
    tagline: 'Monthly Walmart+ membership covered by statement credit.',
    symbol: 'cart.fill',
    category: 'fixed',
    annualCap: 155,
    resetType: 'jan1',
  },
  {
    id: 'resy',
    name: 'Resy Dining Credit',
    tagline: 'Up to $400 a year ($200 semi-annual) on U.S. Resy restaurants.',
    symbol: 'fork.knife',
    category: 'fixed',
    annualCap: 400,
    resetType: 'jan1',
  },
  {
    id: 'lululemon',
    name: 'Lululemon Credit',
    tagline: 'Up to $300 a year on Lululemon, split into quarterly $75 increments.',
    symbol: 'figure.run',
    category: 'fixed',
    annualCap: 300,
    resetType: 'jan1',
  },
  {
    id: 'clear-plus',
    name: 'CLEAR Plus',
    tagline: 'Up to $199 a year toward a CLEAR Plus membership.',
    symbol: 'shield.fill',
    category: 'fixed',
    annualCap: 199,
    resetType: 'jan1',
  },
  {
    id: 'equinox',
    name: 'Equinox',
    tagline: 'Up to $300 a year on an Equinox membership.',
    symbol: 'figure.strengthtraining.functional',
    category: 'fixed',
    annualCap: 300,
    resetType: 'jan1',
  },
  {
    id: 'soulcycle',
    name: 'SoulCycle',
    tagline: 'Up to $300 a year on SoulCycle at-home bike purchases.',
    symbol: 'figure.indoor.cycle',
    category: 'fixed',
    annualCap: 300,
    resetType: 'jan1',
  },
  {
    id: 'global-entry',
    name: 'Global Entry / TSA PreCheck',
    tagline: 'A $100 credit every four years for trusted-traveler programs.',
    symbol: 'globe',
    category: 'fixed',
    annualCap: 100,
    resetType: 'per_use',
  },
  {
    id: 'centurion-lounge',
    name: 'Centurion Lounge',
    tagline: 'Complimentary access to The Centurion Lounge worldwide.',
    symbol: 'sofa.fill',
    category: 'soft',
    annualCap: null,
    resetType: 'jan1',
  },
  {
    id: 'priority-pass',
    name: 'Priority Pass Select',
    tagline: 'Membership covering 1,400+ airport lounges around the world.',
    symbol: 'globe.americas.fill',
    category: 'soft',
    annualCap: null,
    resetType: 'jan1',
  },
  {
    id: 'delta-sky-club',
    name: 'Delta Sky Club',
    tagline: 'Complimentary Sky Club access when flying same-day Delta.',
    symbol: 'airplane.departure',
    category: 'soft',
    annualCap: null,
    resetType: 'jan1',
  },
  {
    id: 'marriott-gold',
    name: 'Marriott Bonvoy Gold',
    tagline: 'Complimentary Gold Elite status with upgrades and bonus points.',
    symbol: 'building.2.fill',
    category: 'soft',
    annualCap: null,
    resetType: 'jan1',
  },
  {
    id: 'hilton-gold',
    name: 'Hilton Honors Gold',
    tagline: 'Complimentary Gold status with bonus points and room upgrades.',
    symbol: 'building.fill',
    category: 'soft',
    annualCap: null,
    resetType: 'jan1',
  },
  {
    id: 'fhr',
    name: 'Fine Hotels + Resorts',
    tagline: '1,500+ properties with daily breakfast, $100 amenity credit, upgrades.',
    symbol: 'star.circle.fill',
    category: 'soft',
    annualCap: null,
    resetType: 'jan1',
  },
  {
    id: 'travel-insurance',
    name: 'Travel & Purchase Protection',
    tagline: 'Trip cancellation, baggage, and purchase coverage on eligible spend.',
    symbol: 'lock.shield.fill',
    category: 'soft',
    annualCap: null,
    resetType: 'jan1',
  },
]

export const findBenefit = (id: string) => BENEFITS.find((b) => b.id === id)
